
set(VISIONCOM_BIN_DIR ${CMAKE_CURRENT_BINARY_DIR}/bin)
set(VISIONCOM_LIB_DIR ${CMAKE_CURRENT_BINARY_DIR}/lib)
set(VISIONCOM_ARCHIVE_DIR ${CMAKE_CURRENT_BINARY_DIR}/lib)

get_filename_component(CURRENT_PATH ${CMAKE_CURRENT_LIST_FILE} PATH)
message(STATUS "module path: "  ${CURRENT_PATH})
set(CMAKE_MODULE_PATH ${CURRENT_PATH})
set(VISIONCOM_BASE_DIR ${CMAKE_MODULE_PATH}/../)
set (VISIONCOM_DATA_PATH ${VISIONCOM_BASE_DIR}data)
message(STATUS "data path: "  ${VISIONCOM_DATA_PATH})